SmartVote:
  image: E-Movement/SmartVote

  ports:
    - "3000:3000"
    - "3005:3005"
    - "30303:30303"

  environment:
    - CONTAINERS=true

  links:
    - ipfs

ipfs:
  image: eris/ipfs

  volumes:
    - ~/.eris/filesystems/ipfs:/root/.ipfs:rw

  ports:
    - "4001:4001"
    - "8080:8080"
